# Generated by Django 4.0.4 on 2022-05-25 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slopelopedia', '0002_location_user_alter_location_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slopelopedia.location'),
        ),
    ]
